name: dart_hangul
description: 한글 자모 분해·조합, 조사 처리, 받침·초성 추출, 숫자 한글 변환 유틸리티. toss/es-hangul 의 Dart 포팅.
version: 0.1.1
repository: https://github.com/JoMinSeo/dart-hangul

environment:
  sdk: ^3.7.2

dependencies:
  unorm_dart: ^0.3.2
dev_dependencies:
  lints: ^5.1.1
  test: ^1.31.0
